<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        // Tell the browser to be responsive to screen width
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?= $this->headLink()
        ->appendStylesheet($this->basePath('css/vendor.css'))
        ->appendStylesheet($this->basePath('css/app.css'))

        ->appendStylesheet($this->basePath('css/plugins/iCheck/custom.css'))

        ->appendStylesheet($this->basePath('css/plugins/datapicker/datepicker3.css'))

        ->appendStylesheet($this->basePath('css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css'))

    ?>

    <!-- FooTable -->
    <link href="css/plugins/footable/footable.core.css" rel="stylesheet">
    

</head>
<body >

  <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        <?php echo $this->render('navigation.phtml') ?>

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            <?php echo $this->render('topnavbar.phtml') ?>

            <!-- Main view  -->
            <div class="wrapper wrapper-content -animated -fadeInRight">
                <?= $this->content ?>
            </div>

            <!-- Footer -->
            <?php echo $this->render('footer.phtml') ?>

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

<?= $this->headScript()
    // jQuery 2.2.3
    ->appendFile($this->basePath('js/app.js'))
?>


  <!-- Mainly scripts -->

  <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>
  <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

  <!-- Flot -->
  <script src="js/plugins/flot/jquery.flot.js"></script>
  <script src="js/plugins/flot/jquery.flot.tooltip.min.js"></script>
  <script src="js/plugins/flot/jquery.flot.spline.js"></script>
  <script src="js/plugins/flot/jquery.flot.resize.js"></script>
  <script src="js/plugins/flot/jquery.flot.pie.js"></script>
  <script src="js/plugins/flot/jquery.flot.symbol.js"></script>
  <script src="js/plugins/flot/jquery.flot.time.js"></script>

  <!-- Custom and plugin javascript -->
  <script src="js/plugins/pace/pace.min.js"></script>

  <!-- FooTable -->
  <script src="js/plugins/footable/footable.all.min.js"></script>

  <!-- Sparkline -->
  <script src="js/plugins/sparkline/jquery.sparkline.min.js"></script>

  <!-- Data picker -->
  <script src="js/plugins/datapicker/bootstrap-datepicker.js"></script>


  <!-- iCheck -->
  <script src="js/plugins/iCheck/icheck.min.js"></script>
  <script>
      $(document).ready(function () {

          $('.input-group.date').datepicker({
              todayBtn: "linked",
              keyboardNavigation: false,
              forceParse: false,
              calendarWeeks: true,
              autoclose: true
          });


          $('.i-checks').iCheck({
              checkboxClass: 'icheckbox_square-green',
              radioClass: 'iradio_square-green',
          });
      });
  </script>


  <script>
      $('.footable').footable();

      $(document).ready(function() {


          var sparklineCharts = function(){
              $("#sparkline1").sparkline([34, 43, 43, 35, 44, 32, 44, 52], {
                  type: 'line',
                  width: '100%',
                  height: '50',
                  lineColor: '#1ab394',
                  fillColor: "transparent"
              });

              $("#sparkline2").sparkline([32, 11, 25, 37, 41, 32, 34, 42], {
                  type: 'line',
                  width: '100%',
                  height: '50',
                  lineColor: '#1ab394',
                  fillColor: "transparent"
              });

              $("#sparkline3").sparkline([34, 22, 24, 41, 10, 18, 16,8], {
                  type: 'line',
                  width: '100%',
                  height: '50',
                  lineColor: '#1C84C6',
                  fillColor: "transparent"
              });
          };

          var sparkResize;

          $(window).resize(function(e) {
              clearTimeout(sparkResize);
              sparkResize = setTimeout(sparklineCharts, 500);
          });

          sparklineCharts();




          var data1 = [
              [0,4],[1,8],[2,5],[3,10],[4,4],[5,16],[6,5],[7,11],[8,6],[9,11],[10,20],[11,10],[12,13],[13,4],[14,7],[15,8],[16,12]
          ];
          var data2 = [
              [0,0],[1,2],[2,7],[3,4],[4,11],[5,4],[6,2],[7,5],[8,11],[9,5],[10,4],[11,1],[12,5],[13,2],[14,5],[15,2],[16,0]
          ];
          $("#flot-dashboard5-chart").length && $.plot($("#flot-dashboard5-chart"), [
                  data1,  data2
              ],
              {
                  series: {
                      lines: {
                          show: false,
                          fill: true
                      },
                      splines: {
                          show: true,
                          tension: 0.4,
                          lineWidth: 1,
                          fill: 0.4
                      },
                      points: {
                          radius: 0,
                          show: true
                      },
                      shadowSize: 2
                  },
                  grid: {
                      hoverable: true,
                      clickable: true,

                      borderWidth: 2,
                      color: 'transparent'
                  },
                  colors: ["#1ab394", "#1C84C6"],
                  xaxis:{
                  },
                  yaxis: {
                  },
                  tooltip: false
              }
          );

      });
  </script>





</body>
</html>
