<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Usuário</strong>
                            </span> <span class="text-muted text-xs block">Pérola do Oeste<b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Sair</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            <li class="<?= $this->currentRoute()->isActive('home')?>">
                <a href="/"><i class="fa fa-th-large"></i> <span class="nav-label">Main view</span></a>
            </li>
            <li class="<?= $this->currentRoute()->isActive('agencia')?>">
                <a href="/agencia"><i class="fa fa-th-large"></i> <span class="nav-label">Agências</span> </a>
            </li>
            <li class="<?= $this->currentRoute()->isActive('rota')?>">
                <a href="/rota"><i class="fa fa-th-large"></i> <span class="nav-label">Rotas</span> </a>
            </li>
            <li class="<?= $this->currentRoute()->isActive('parada')?>">
                <a href="/parada"><i class="fa fa-th-large"></i> <span class="nav-label">Paradas</span> </a>
            </li>

            <li class="<?= $this->currentRoute()->isActive('viagem')?>">
                <a href="/viagem"><i class="fa fa-th-large"></i> <span class="nav-label">Viagens</span> </a>
            </li>

            <li>
                <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label">Menu Levels </span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li>
                        <a href="#">Third Level <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level collapse">
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>

                        </ul>
                    </li>
                    <li><a href="#"><span class="fa fa-fw fa-code-fork"></span>Second Level Item</a></li>
                    <li>
                        <a href="#">Second Level Item</a></li>
                    <li>
                        <a href="#">Second Level Item</a></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>
